server:
  port: 9011 # 设置WebApp端口

spring:
  application:
    name: hello-server # 设置WebApp名称，在spring cloud会被注册为服务名
#  profiles:
#    active: server2

eureka:
  instance:
    prefer-ip-address: true # 设置以Ip地址形式来定义注册中心的地址，默认false，以主机名形式
    virtual-host-name: helloserver
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

# @PropertySource注解可加载properties文件配置，yaml文件配置则不可以

# yaml可在单一文件中定义不同环境的配置，使用spring.profiles来定义{profileName}
# properties一个文件只能定义一个环境的配置，使用application-{profileName}.properties
# 可使用spring.profiles.active来指定环境配置
---
### server2环境配置 ###
 spring:
   profiles: server2
 server:
   port: 9012 # 针对server2配置：设置WebApp端口，覆盖通用设置
---
### server3环境配置 ###
 spring:
   profiles: server3
 server:
   port: 9013 # 针对server3配置：设置WebApp端口，覆盖通用设置